### ISSUE TITLE
Prompt before checking IP (or remove it and prompt for Tor)

### ISSUE THREAD

**Issue by sleep3** [tornadocash/tornado-cli#32]
The IP check contacts a tornado cash domain, and it might do this over the clear net. Either people should be prompted before doing the IP check or we should remove the IP check in totality and prompt if the user is not connecting over a Tor port.

Case: User runs a local node that is not over Tor and connects to it. Boom, without warning tornado-cli contacts a tornado cash domain name and now their system administrator and ISP knows they were using tornado.

**Comment by 0xAyanami** [comment]
@sleep3 Would be great if we could have an alternative for ip.tornado.cash, since it is the only API endpoint to fetch remote IP address from tor without facing issues with Cloudflare, firewalls, etc.

Reference: https://github.com/mpolden/echoip/issues/74#issuecomment-576301441

Also, excluding localhost connection for showing remote IP address could be another option as well.

**Comment by poma** [comment]
ip.tornado.cash request was removed from the UI so the server will be shutting down soon. It was running an ip-echo container.

**Comment by 0xAyanami** [comment]
So this is where we need to replace it, thanks @poma !
